class: var-recovery: change task depends to work with rm_work
tasks depending on do_build will trigger extend_recipe_sysroot, which
causes errors in the extend_recipe_sysroot when INHERIT += "rm_work" is
added to local.conf:

    Exception: FileExistsError: [Errno 17] File exists: '<redacted>/tmp/sysroots-components/armv8a/libgcc-initial/usr/lib/aarch64-poky-linux/12.2.0/crtfastmath.o' -> '<redacted>/tmp/work/imx8mp_var_dart-poky-linux/var-recovery-image/1.0-r0/recipe-sysroot/usr/lib/aarch64-poky-linux/12.2.0/crtfastmath.o'

This may be related to https://git.yoctoproject.org/poky/commit/?id=1c115da

To avoid this altogether, this patch specifies the task dependencies
more precisely by using do_deploy and do_image_complete, thereby avoiding
triggering extend_recipe_sysroot.

Signed-off-by: Nate Drude <nate.d@variscite.com>